In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings

warnings.filterwarnings("ignore")

print("Libraries Imported Successfully")

Libraries Imported Successfully

In [3]:
logon = pd.read_csv("/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/r4.2/logon.csv")
device = pd.read_csv("/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/r4.2/device.csv")
email = pd.read_csv("/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/r4.2/email.csv")
file = pd.read_csv("/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/r4.2/file.csv")
http = pd.read_csv("/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/r4.2/http.csv")

print("All datasets loaded successfully")

All datasets loaded successfully

In [4]:
datasets = {
    "Logon": logon,
    "Device": device,
    "Email": email,
    "File": file,
    "HTTP": http
}

for name, df in datasets.items():
    print("=" * 50)
    print(name)
    print("=" * 50)
    print("Shape :", df.shape)
    print("\nColumns")
    print(df.columns.tolist())
    print("\nFirst 5 Rows")
    display(df.head())

==================================================
Logon
==================================================
Shape : (854859, 5)

Columns
['id', 'date', 'user', 'pc', 'activity']

First 5 Rows

                         id                 date     user       pc activity
0  {X1D9-S0ES98JV-5357PWMI}  01/02/2010 06:49:00  NGF0157  PC-6056    Logon
1  {G2B3-L6EJ61GT-2222RKSO}  01/02/2010 06:50:00  LRR0148  PC-4275    Logon
2  {U6Q3-U0WE70UA-3770UREL}  01/02/2010 06:53:04  LRR0148  PC-4124    Logon
3  {I0N5-R7NA26TG-6263KNGM}  01/02/2010 07:00:00  IRM0931  PC-7188    Logon
4  {D1S0-N6FH62BT-5398KANK}  01/02/2010 07:00:00  MOH0273  PC-6699    Logon

==================================================
Device
==================================================
Shape : (405380, 5)

Columns
['id', 'date', 'user', 'pc', 'activity']

First 5 Rows

                         id                 date     user       pc    activity
0  {J1S3-L9UU75BQ-7790ATPL}  01/02/2010 07:21:06  MOH0273  PC-6699     Connect
1  {N7B5-Y7BB27SI-2946PUJK}  01/02/2010 07:37:41  MOH0273  PC-6699  Disconnect
2  {U1V9-Z7XT67KV-5649MYHI}  01/02/2010 07:59:11  HPH0075  PC-2417     Connect
3  {H0Z7-E6GB57XZ-1603MOXD}  01/02/2010 07:59:49  IIW0249  PC-0843     Connect
4  {L7P2-G4PX02RX-7999GYOY}  01/02/2010 08:04:26  IIW0249  PC-0843  Disconnect

==================================================
Email
==================================================
Shape : (2629979, 11)

Columns
['id', 'date', 'user', 'pc', 'to', 'cc', 'bcc', 'from', 'size', 'attachments', 'content']

First 5 Rows

,id,date,user,pc,to,cc,bcc,from,size,attachments,content
0,{R3I7-S4TX96FG-8219JWFF},01/02/2010 07:11:45,LAP0338,PC-5758,Dean.Flynn.Hines@dtaa.com;Wade_Harrison@lockhe...,Nathaniel.Hunter.Heath@dtaa.com,NaN,Lynn.Adena.Pratt@dtaa.com,25830,0,middle f2 systems 4 july techniques powerful d...
1,{R0R9-E4GL59IK-2907OSWJ},01/02/2010 07:12:16,MOH0273,PC-6699,Odonnell-Gage@bellsouth.net,NaN,NaN,MOH68@optonline.net,29942,0,the breaking called allied reservations former...
2,{G2B2-A8XY58CP-2847ZJZL},01/02/2010 07:13:00,LAP0338,PC-5758,Penelope_Colon@netzero.com,NaN,NaN,Lynn_A_Pratt@earthlink.net,28780,0,slowly this uncinus winter beneath addition ex...
3,{A3A9-F4TH89AA-8318GFGK},01/02/2010 07:13:17,LAP0338,PC-5758,Judith_Hayden@comcast.net,NaN,NaN,Lynn_A_Pratt@earthlink.net,21907,0,400 other difficult land cirrocumulus powered ...
4,{E8B7-C8FZ88UF-2946RUQQ},01/02/2010 07:13:28,MOH0273,PC-6699,Bond-Raymond@verizon.net;Alea_Ferrell@msn.com;...,NaN,Odonnell-Gage@bellsouth.net,MOH68@optonline.net,17319,0,this kmh october holliswood number advised unu...

==================================================
File
==================================================
Shape : (445581, 6)

Columns
['id', 'date', 'user', 'pc', 'filename', 'content']

First 5 Rows

,id,date,user,pc,filename,content
0,{L9G8-J9QE34VM-2834VDPB},01/02/2010 07:23:14,MOH0273,PC-6699,EYPC9Y08.doc,D0-CF-11-E0-A1-B1-1A-E1 during difficulty over...
1,{H0W6-L4FG38XG-9897XTEN},01/02/2010 07:26:19,MOH0273,PC-6699,N3LTSU3O.pdf,25-50-44-46-2D carpenters 25 landed strait dis...
2,{M3Z0-O2KK89OX-5716MBIM},01/02/2010 08:12:03,HPH0075,PC-2417,D3D3WC9W.doc,D0-CF-11-E0-A1-B1-1A-E1 union 24 declined impo...
3,{E1I4-S4QS61TG-3652YHKR},01/02/2010 08:17:00,HPH0075,PC-2417,QCSW62YS.doc,D0-CF-11-E0-A1-B1-1A-E1 becoming period begin ...
4,{D4R7-E7JL45UX-0067XALT},01/02/2010 08:24:57,HSB0196,PC-8001,AU75JV6U.jpg,FF-D8

==================================================
HTTP
==================================================
Shape : (28434423, 6)

Columns
['id', 'date', 'user', 'pc', 'url', 'content']

First 5 Rows

,id,date,user,pc,url,content
0,{V1Y4-S2IR20QU-6154HFXJ},01/02/2010 06:55:16,LRR0148,PC-4275,http://msn.com/The_Human_Centipede_First_Seque...,remain representatives consensus concert altho...
1,{Q5R1-T3EF87UE-2395RWZS},01/02/2010 07:00:13,NGF0157,PC-6056,http://urbanspoon.com/Plunketts_Creek_Loyalsoc...,festival off northwards than congestion partne...
2,{X9O1-O0XW52VO-5806RPHG},01/02/2010 07:03:46,NGF0157,PC-6056,http://aa.com/Rhodocene/rhodocenium/fhaavatqrf...,long away reorganized baldwin seth business 18...
3,{G5S8-U5OG04TE-5299CCTU},01/02/2010 07:05:26,IRM0931,PC-7188,http://groupon.com/Leonhard_Euler/leonhard/tne...,among german schwein experimental becomes prev...
4,{L0R4-A9DH29VP-4553AUWM},01/02/2010 07:05:52,IRM0931,PC-7188,http://flickr.com/Inauguration_of_Barack_Obama...,kate criteria j 2008 highest 12 include books ...

In [5]:
print("LOGON")
print(logon.isnull().sum())

print("\nDEVICE")
print(device.isnull().sum())

print("\nEMAIL")
print(email.isnull().sum())

print("\nFILE")
print(file.isnull().sum())

print("\nHTTP")
print(http.isnull().sum())

LOGON
id          0
date        0
user        0
pc          0
activity    0
dtype: int64

DEVICE
id          0
date        0
user        0
pc          0
activity    0
dtype: int64

EMAIL
id                   0
date                 0
user                 0
pc                   0
to                   0
cc             1617054
bcc            2212977
from                 0
size                 0
attachments          0
content              0
dtype: int64

FILE
id          0
date        0
user        0
pc          0
filename    0
content     0
dtype: int64

HTTP
id         0
date       0
user       0
pc         0
url        0
content    0
dtype: int64

In [6]:
logon['date'] = pd.to_datetime(logon['date'])
device['date'] = pd.to_datetime(device['date'])
email['date'] = pd.to_datetime(email['date'])
file['date'] = pd.to_datetime(file['date'])
http['date'] = pd.to_datetime(http['date'])

print("Date Conversion Completed")

Date Conversion Completed

In [10]:
datasets = [logon, device, email, file, http]

for df in datasets:
    df['hour'] = df['date'].dt.hour
    df['day'] = df['date'].dt.day
    df['month'] = df['date'].dt.month
    df['year'] = df['date'].dt

print("Time Features Created Successfully")

Time Features Created Successfully

In [11]:
print("LOGON")
display(logon.head())

print("DEVICE")
display(device.head())

print("EMAIL")
display(email.head())

print("FILE")
display(file.head())

print("HTTP")
display(http.head())

LOGON

,id,date,user,pc,activity,hour,day,month,year
0,{X1D9-S0ES98JV-5357PWMI},2010-01-02 06:49:00,NGF0157,PC-6056,Logon,6,2,1,<pandas.core.indexes.accessors.DatetimePropert...
1,{G2B3-L6EJ61GT-2222RKSO},2010-01-02 06:50:00,LRR0148,PC-4275,Logon,6,2,1,<pandas.core.indexes.accessors.DatetimePropert...
2,{U6Q3-U0WE70UA-3770UREL},2010-01-02 06:53:04,LRR0148,PC-4124,Logon,6,2,1,<pandas.core.indexes.accessors.DatetimePropert...
3,{I0N5-R7NA26TG-6263KNGM},2010-01-02 07:00:00,IRM0931,PC-7188,Logon,7,2,1,<pandas.core.indexes.accessors.DatetimePropert...
4,{D1S0-N6FH62BT-5398KANK},2010-01-02 07:00:00,MOH0273,PC-6699,Logon,7,2,1,<pandas.core.indexes.accessors.DatetimePropert...

DEVICE

,id,date,user,pc,activity,hour,day,month,year
0,{J1S3-L9UU75BQ-7790ATPL},2010-01-02 07:21:06,MOH0273,PC-6699,Connect,7,2,1,<pandas.core.indexes.accessors.DatetimePropert...
1,{N7B5-Y7BB27SI-2946PUJK},2010-01-02 07:37:41,MOH0273,PC-6699,Disconnect,7,2,1,<pandas.core.indexes.accessors.DatetimePropert...
2,{U1V9-Z7XT67KV-5649MYHI},2010-01-02 07:59:11,HPH0075,PC-2417,Connect,7,2,1,<pandas.core.indexes.accessors.DatetimePropert...
3,{H0Z7-E6GB57XZ-1603MOXD},2010-01-02 07:59:49,IIW0249,PC-0843,Connect,7,2,1,<pandas.core.indexes.accessors.DatetimePropert...
4,{L7P2-G4PX02RX-7999GYOY},2010-01-02 08:04:26,IIW0249,PC-0843,Disconnect,8,2,1,<pandas.core.indexes.accessors.DatetimePropert...

EMAIL

,id,date,user,pc,to,cc,bcc,from,size,attachments,content,hour,day,month,year
0,{R3I7-S4TX96FG-8219JWFF},2010-01-02 07:11:45,LAP0338,PC-5758,Dean.Flynn.Hines@dtaa.com;Wade_Harrison@lockhe...,Nathaniel.Hunter.Heath@dtaa.com,NaN,Lynn.Adena.Pratt@dtaa.com,25830,0,middle f2 systems 4 july techniques powerful d...,7,2,1,<pandas.core.indexes.accessors.DatetimePropert...
1,{R0R9-E4GL59IK-2907OSWJ},2010-01-02 07:12:16,MOH0273,PC-6699,Odonnell-Gage@bellsouth.net,NaN,NaN,MOH68@optonline.net,29942,0,the breaking called allied reservations former...,7,2,1,<pandas.core.indexes.accessors.DatetimePropert...
2,{G2B2-A8XY58CP-2847ZJZL},2010-01-02 07:13:00,LAP0338,PC-5758,Penelope_Colon@netzero.com,NaN,NaN,Lynn_A_Pratt@earthlink.net,28780,0,slowly this uncinus winter beneath addition ex...,7,2,1,<pandas.core.indexes.accessors.DatetimePropert...
3,{A3A9-F4TH89AA-8318GFGK},2010-01-02 07:13:17,LAP0338,PC-5758,Judith_Hayden@comcast.net,NaN,NaN,Lynn_A_Pratt@earthlink.net,21907,0,400 other difficult land cirrocumulus powered ...,7,2,1,<pandas.core.indexes.accessors.DatetimePropert...
4,{E8B7-C8FZ88UF-2946RUQQ},2010-01-02 07:13:28,MOH0273,PC-6699,Bond-Raymond@verizon.net;Alea_Ferrell@msn.com;...,NaN,Odonnell-Gage@bellsouth.net,MOH68@optonline.net,17319,0,this kmh october holliswood number advised unu...,7,2,1,<pandas.core.indexes.accessors.DatetimePropert...

FILE

,id,date,user,pc,filename,content,hour,day,month,year
0,{L9G8-J9QE34VM-2834VDPB},2010-01-02 07:23:14,MOH0273,PC-6699,EYPC9Y08.doc,D0-CF-11-E0-A1-B1-1A-E1 during difficulty over...,7,2,1,<pandas.core.indexes.accessors.DatetimePropert...
1,{H0W6-L4FG38XG-9897XTEN},2010-01-02 07:26:19,MOH0273,PC-6699,N3LTSU3O.pdf,25-50-44-46-2D carpenters 25 landed strait dis...,7,2,1,<pandas.core.indexes.accessors.DatetimePropert...
2,{M3Z0-O2KK89OX-5716MBIM},2010-01-02 08:12:03,HPH0075,PC-2417,D3D3WC9W.doc,D0-CF-11-E0-A1-B1-1A-E1 union 24 declined impo...,8,2,1,<pandas.core.indexes.accessors.DatetimePropert...
3,{E1I4-S4QS61TG-3652YHKR},2010-01-02 08:17:00,HPH0075,PC-2417,QCSW62YS.doc,D0-CF-11-E0-A1-B1-1A-E1 becoming period begin ...,8,2,1,<pandas.core.indexes.accessors.DatetimePropert...
4,{D4R7-E7JL45UX-0067XALT},2010-01-02 08:24:57,HSB0196,PC-8001,AU75JV6U.jpg,FF-D8,8,2,1,<pandas.core.indexes.accessors.DatetimePropert...

HTTP

,id,date,user,pc,url,content,hour,day,month,year
0,{V1Y4-S2IR20QU-6154HFXJ},2010-01-02 06:55:16,LRR0148,PC-4275,http://msn.com/The_Human_Centipede_First_Seque...,remain representatives consensus concert altho...,6,2,1,<pandas.core.indexes.accessors.DatetimePropert...
1,{Q5R1-T3EF87UE-2395RWZS},2010-01-02 07:00:13,NGF0157,PC-6056,http://urbanspoon.com/Plunketts_Creek_Loyalsoc...,festival off northwards than congestion partne...,7,2,1,<pandas.core.indexes.accessors.DatetimePropert...
2,{X9O1-O0XW52VO-5806RPHG},2010-01-02 07:03:46,NGF0157,PC-6056,http://aa.com/Rhodocene/rhodocenium/fhaavatqrf...,long away reorganized baldwin seth business 18...,7,2,1,<pandas.core.indexes.accessors.DatetimePropert...
3,{G5S8-U5OG04TE-5299CCTU},2010-01-02 07:05:26,IRM0931,PC-7188,http://groupon.com/Leonhard_Euler/leonhard/tne...,among german schwein experimental becomes prev...,7,2,1,<pandas.core.indexes.accessors.DatetimePropert...
4,{L0R4-A9DH29VP-4553AUWM},2010-01-02 07:05:52,IRM0931,PC-7188,http://flickr.com/Inauguration_of_Barack_Obama...,kate criteria j 2008 highest 12 include books ...,7,2,1,<pandas.core.indexes.accessors.DatetimePropert...

In [12]:
print("Logon :", logon.shape)
print("Device :", device.shape)
print("Email :", email.shape)
print("File :", file.shape)
print("HTTP :", http.shape)

Logon : (854859, 9)
Device : (405380, 9)
Email : (2629979, 15)
File : (445581, 10)
HTTP : (28434423, 10)

In [14]:
import os

for root, dirs, files in os.walk("/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2"):
    for file_name in files:
        print(os.path.join(root, file_name))

/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/answers/readme.txt
/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/answers/scenarios.txt
/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/answers/license.txt
/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/answers/insiders.csv
/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/answers/r4.2-2/r4.2-2-MOS0047.csv
/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/answers/r4.2-2/r4.2-2-IKR0401.csv
/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/answers/r4.2-2/r4.2-2-DRR0162.csv
/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/answers/r4.2-2/r4.2-2-CQW0652.csv
/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/answers/r4.2-2/r4.2-2-PSF0133.csv
/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/answers/r4.2-2/r4.2-2-KRL0501.csv
/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/answers/r4.2-2/r4.2-2-EGD0132.csv
/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/answers/r4.2-2/r4.2-2-RHL0992.csv
/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/answers/r4.2-2/r4.2-2-VSS0154.csv
/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/answers/r4.2-2/r4.2-2-HBO0413.csv
/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/answers/r4.2-2/r4.2-2-ABC0174.csv
/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/answers/r4.2-2/r4.2-2-AKR0057.csv
/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/answers/r4.2-2/r4.2-2-RMW0542.csv
/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/answers/r4.2-2/r4.2-2-AAF0535.csv
/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/answers/r4.2-2/r4.2-2-FSC0601.csv
/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/answers/r4.2-2/r4.2-2-TNM0961.csv
/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/answers/r4.2-2/r4.2-2-EDB0714.csv
/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/answers/r4.2-2/r4.2-2-XHW0498.csv
/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/answers/r4.2-2/r4.2-2-HXL0968.csv
/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/answers/r4.2-2/r4.2-2-PNL0301.csv
/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/answers/r4.2-2/r4.2-2-NWT0098.csv
/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/answers/r4.2-2/r4.2-2-CCL0068.csv
/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/answers/r4.2-2/r4.2-2-JJM0203.csv
/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/answers/r4.2-2/r4.2-2-RAR0725.csv
/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/answers/r4.2-2/r4.2-2-CEJ0109.csv
/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/answers/r4.2-2/r4.2-2-LCC0819.csv
/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/answers/r4.2-2/r4.2-2-MDH0580.csv
/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/answers/r4.2-2/r4.2-2-IUB0565.csv
/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/answers/r4.2-2/r4.2-2-DIB0285.csv
/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/answers/r4.2-2/r4.2-2-IJM0776.csv
/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/answers/r4.2-3/r4.2-3-BSS0369.csv
/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/answers/r4.2-3/r4.2-3-GTD0219.csv
/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/answers/r4.2-3/r4.2-3-JLM0364.csv
/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/answers/r4.2-3/r4.2-3-JTM0223.csv
/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/answers/r4.2-3/r4.2-3-CSC0217.csv
/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/answers/r4.2-3/r4.2-3-CCA0046.csv
/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/answers/r4.2-3/r4.2-3-MSO0222.csv
/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/answers/r4.2-3/r4.2-3-MPM0220.csv
/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/answers/r4.2-3/r4.2-3-JGT0221.csv
/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/answers/r4.2-3/r4.2-3-BBS0039.csv
/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/answers/r4.2-1/r4.2-1-MYD0978.csv
/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/answers/r4.2-1/r4.2-1-LJR0523.csv
/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/answers/r4.2-1/r4.2-1-BDV0168.csv
/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/answers/r4.2-1/r4.2-1-CAH0936.csv
/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/answers/r4.2-1/r4.2-1-GHL0460.csv
/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/answers/r4.2-1/r4.2-1-RGG0064.csv
/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/answers/r4.2-1/r4.2-1-BTL0226.csv
/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/answers/r4.2-1/r4.2-1-JMB0308.csv
/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/answers/r4.2-1/r4.2-1-FTM0406.csv
/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/answers/r4.2-1/r4.2-1-KPC0073.csv
/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/answers/r4.2-1/r4.2-1-MAR0955.csv
/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/answers/r4.2-1/r4.2-1-KLH0596.csv
/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/answers/r4.2-1/r4.2-1-MCF0600.csv
/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/answers/r4.2-1/r4.2-1-RAB0589.csv
/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/answers/r4.2-1/r4.2-1-HJB0742.csv
/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/answers/r4.2-1/r4.2-1-MAS0025.csv
/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/answers/r4.2-1/r4.2-1-WDD0366.csv
/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/answers/r4.2-1/r4.2-1-LQC0479.csv
/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/answers/r4.2-1/r4.2-1-EHB0824.csv
/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/answers/r4.2-1/r4.2-1-DCH0843.csv
/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/answers/r4.2-1/r4.2-1-EHD0584.csv
/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/answers/r4.2-1/r4.2-1-PPF0435.csv
/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/answers/r4.2-1/r4.2-1-RKD0604.csv
/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/answers/r4.2-1/r4.2-1-FMG0527.csv
/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/answers/r4.2-1/r4.2-1-BIH0745.csv
/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/answers/r4.2-1/r4.2-1-JRG0207.csv
/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/answers/r4.2-1/r4.2-1-BLS0678.csv
/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/answers/r4.2-1/r4.2-1-AJR0932.csv
/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/answers/r4.2-1/r4.2-1-AAM0658.csv
/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/answers/r4.2-1/r4.2-1-TAP0551.csv
/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/r4.2/logon.csv
/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/r4.2/device.csv
/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/r4.2/psychometric.csv
/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/r4.2/http.csv
/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/r4.2/readme.txt
/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/r4.2/license.txt
/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/r4.2/email.csv
/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/r4.2/file.csv
/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/r4.2/LDAP/2010-08.csv
/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/r4.2/LDAP/2011-03.csv
/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/r4.2/LDAP/2010-10.csv
/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/r4.2/LDAP/2010-02.csv
/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/r4.2/LDAP/2010-03.csv
/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/r4.2/LDAP/2010-09.csv
/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/r4.2/LDAP/2011-04.csv
/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/r4.2/LDAP/2009-12.csv
/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/r4.2/LDAP/2010-06.csv
/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/r4.2/LDAP/2010-07.csv
/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/r4.2/LDAP/2010-05.csv
/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/r4.2/LDAP/2010-11.csv
/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/r4.2/LDAP/2010-04.csv
/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/r4.2/LDAP/2010-12.csv
/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/r4.2/LDAP/2011-01.csv
/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/r4.2/LDAP/2011-02.csv
/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/r4.2/LDAP/2011-05.csv
/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/r4.2/LDAP/2010-01.csv

In [15]:
insiders = pd.read_csv(
    "/kaggle/input/datasets/andrihjonior/cert-insider-threat-dataset-r4-2/answers/insiders.csv"
)

insiders.head()

,dataset,scenario,details,user,start,end
0,2.0,1,r2.csv,ONS0995,3/6/2010 1:41:56,3/20/2010 8:10:12
1,3.1,1,r3.1-1.csv,CSF0929,07/01/2010 01:24:58,07/16/2010 06:52:00
2,3.1,2,r3.1-2.csv,CCH0959,08/02/2010 10:34:31,09/30/2010 15:04:03
3,3.2,1,r3.2-1.csv,RCW0822,09/29/2010 21:10:27,10/15/2010 06:34:52
4,3.2,2,r3.2-2.csv,JCE0258,07/12/2010 08:16:02,09/03/2010 16:16:29

In [16]:
print(insiders.shape)
print(insiders.columns)

(191, 6)
Index(['dataset', 'scenario', 'details', 'user', 'start', 'end'], dtype='object')

In [17]:
insiders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 191 entries, 0 to 190
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   dataset   191 non-null    float64
 1   scenario  191 non-null    int64
 2   details   191 non-null    object
 3   user      191 non-null    object
 4   start     191 non-null    object
 5   end       191 non-null    object
dtypes: float64(1), int64(1), object(4)
memory usage: 9.1+ KB

In [19]:
insiders['start'] = pd.to_datetime(
    insiders['start'],
    format='mixed',
    errors='coerce'
)

insiders['end'] = pd.to_datetime(
    insiders['end'],
    format='mixed',
    errors='coerce'
)

print(insiders[['start', 'end']].isnull().sum())

start    1
end      0
dtype: int64

In [20]:
insiders[insiders['start'].isna() | insiders['end'].isna()]

     dataset  scenario     details     user start                 end
189      6.2         4  r6.2-4.csv  CDE1846   NaT 2011-04-25 17:55:00

In [21]:
insiders = insiders.dropna(subset=['start', 'end'])

print("Remaining rows:", len(insiders))

Remaining rows: 190

In [22]:
insider_users = insiders['user'].unique()

print("Total Insider Users:", len(insider_users))
print(insider_users[:10])

Total Insider Users: 190
['ONS0995' 'CSF0929' 'CCH0959' 'RCW0822' 'JCE0258' 'ABB0427' 'HFC0492'
 'KTW0365' 'AAM0658' 'AJR0932']

In [23]:
logon['label'] = logon['user'].isin(insider_users).astype(int)
device['label'] = device['user'].isin(insider_users).astype(int)
email['label'] = email['user'].isin(insider_users).astype(int)
file['label'] = file['user'].isin(insider_users).astype(int)
http['label'] = http['user'].isin(insider_users).astype(int)

print("Labels created successfully")

Labels created successfully

In [24]:
print("Logon")
print(logon['label'].value_counts())

print("\nDevice")
print(device['label'].value_counts())

print("\nEmail")
print(email['label'].value_counts())

print("\nFile")
print(file['label'].value_counts())

print("\nHTTP")
print(http['label'].value_counts())

Logon
label
0    805332
1     49527
Name: count, dtype: int64

Device
label
0    361246
1     44134
Name: count, dtype: int64

Email
label
0    2510146
1     119833
Name: count, dtype: int64

File
label
0    416898
1     28683
Name: count, dtype: int64

HTTP
label
0    27128445
1     1305978
Name: count, dtype: int64